# Generated by Django 5.2.12 on 2026-04-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_gallery_master_master_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='master',
        ),
        migrations.RemoveField(
            model_name='master',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('master', 'Master'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
